//Should fail if variable already exists
x: int = 3;
fn foo(x: float): int {
    return x;
}
